# Generated by Django 4.2.2 on 2024-09-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=15)),
                ('pubdate', models.DateField()),
                ('startIndex', models.IntegerField()),
                ('pricesales', models.IntegerField()),
                ('adult', models.BooleanField()),
                ('ISBN', models.IntegerField()),
                ('customerReviewRank', models.IntegerField()),
            ],
        ),
    ]
