# Generated by Django 4.2.11 on 2024-10-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(related_name='in_participant', to='events.participant'),
        ),
    ]
