# Generated by Django 4.2.11 on 2024-10-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='context',
            new_name='content',
        ),
    ]
