# Generated by Django 4.2.9 on 2024-09-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
